### ISSUE TITLE
training loss curve

### ISSUE THREAD

**Issue by Adazzh** [hhguo/MSMC-TTS#5]
Could you show us your training loss curve please, i don't know whether my training loss is normal/(ㄒoㄒ)/~~

**Comment by hhguo** [comment]
Training loss curves may vary w.r.t. different datasets. If you have any problems with your training loss, you may post your curves here. I can help check it.

**Comment by Adazzh** [comment]
I use the CSMSC datasets, and my training loss as follows, could you please take a look please? thinks(*^_^*)
![image](https://user-images.githubusercontent.com/53960296/199707362-1634e0f7-31ad-49ae-aad7-4979b745c1c8.png)

![image](https://user-images.githubusercontent.com/53960296/199707203-e269758c-01f3-4003-b74b-1a8cd9ef94e6.png)

![image](https://user-images.githubusercontent.com/53960296/199707493-7860934f-d940-4441-b125-68f2dd96b51a.png)

![image](https://user-images.githubusercontent.com/53960296/199707741-945033e1-402f-435c-8b7b-46080c1ef45c.png)

![image](https://user-images.githubusercontent.com/53960296/199708082-8313cc31-ee7d-4e4e-8da4-15aca5804b4a.png)

![image](https://user-images.githubusercontent.com/53960296/199708312-a52bbb1c-2ac4-44a6-8c78-93cdc0ca0b00.png)

**Comment by Adazzh** [comment]
> I use the CSMSC datasets, and my training loss as follows, could you please take a look please? thinks(_^_^_) ![image](https://user-images.githubusercontent.com/53960296/199707362-1634e0f7-31ad-49ae-aad7-4979b745c1c8.png)
> 
> ![image](https://user-images.githubusercontent.com/53960296/199707203-e269758c-01f3-4003-b74b-1a8cd9ef94e6.png)
> 
> ![image](https://user-images.githubusercontent.com/53960296/199707493-7860934f-d940-4441-b125-68f2dd96b51a.png)
> 
> ![image](https://user-images.githubusercontent.com/53960296/199707741-945033e1-402f-435c-8b7b-46080c1ef45c.png)
> 
> ![image](https://user-images.githubusercontent.com/53960296/199708082-8313cc31-ee7d-4e4e-8da4-15aca5804b4a.png)
> 
> ![image](https://user-images.githubusercontent.com/53960296/1

**Comment by hhguo** [comment]
The trends look OK. You may try analysis-synthesis to see if the waveform is generated well.

**Comment by Adazzh** [comment]
> 

thank you, I've tried but i'm not sure whether it should be better, I'll train more iterations and then try again. o(*￣▽￣*)ブ
